name: Build Binary

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
    - name: Build binary
      run: |
        pyinstaller --onefile your_script.py
    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: your-script-binary
        path: dist/your_script
