name: Build and Push Docker Container

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: artv1d
        password: 1234567ab

    - name: Build and push
      run: |
        docker build -t Artv1d/devops:pr-${{ github.event.number }} .
        docker push Artv1d/devops:pr-${{ github.event.number }}
